name: Fetch data (hourly)

on:
  schedule:
    - cron: "0 * * * *"   # every hour, on the hour (UTC)
  workflow_dispatch: {}    # allow manual runs from the Actions tab

permissions:
  contents: write

jobs:
  run-r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("readr","dplyr","httr2"), repos="https://cloud.r-project.org")'

      - name: Run script
        run: Rscript R/script.R

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.csv || true
          git diff --staged --quiet && echo "No changes" || git commit -m "Update data.csv"
          git push
